version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - postgres.env
    networks:
      - JobzNetwork
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /code/jobz
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    env_file:
      - postgres.env
    networks:
      - JobzNetwork
    depends_on:
      - db
networks:
  JobzNetwork:
    # Use a custom driver
    driver: bridge