# Generated by Django 4.0.2 on 2022-04-01 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('user', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='search.occupation'),
        ),
        migrations.AddField(
            model_name='services',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.provider'),
        ),
        migrations.AddField(
            model_name='services',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.user'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datePurchase',
            field=models.DateField(auto_now=True),
        ),
    ]
