# Generated by Django 4.0.2 on 2022-04-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_services_occupation_services_provider_services_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='dateSevice',
            new_name='dateService',
        ),
    ]
