# Generated by Django 4.0.2 on 2022-04-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_datesevice_services_dateservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='serviceDesription',
            new_name='serviceDescription',
        ),
    ]
