# Generated by Django 4.0.2 on 2022-04-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_provider_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.CharField(choices=[('--', 'Dia da Semana'), ('seg', 'Segunda-Feira'), ('ter', 'Terça-Feira'), ('qua', 'Quarta-Feira'), ('qui', 'Quinta-Feira'), ('sex', 'Sexta-Feira'), ('sab', 'Sábado'), ('dom', 'Domingo')], default='--', max_length=25, unique=True)),
                ('entryTime', models.TimeField()),
                ('endOfWork', models.TimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.provider')),
            ],
        ),
    ]
