# Generated by Django 4.0.2 on 2022-04-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(choices=[('--', 'Categoria de Serviço'), ('Encanador', 'Encanador'), ('Diarista', 'Diarista'), ('Pedreiro', 'Pedreiro'), ('Tecnico', 'Tecnico')], default='--', max_length=25, unique=True)),
            ],
        ),
    ]
