name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t backend
    - name: Tag
      run: docker tag backend antonioaldisio/backend
    - name: Docker configure
      run: docker login
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSOWRD_ANTONIO }}
    - name: pull
      run: docker pull antonioaldisio/backend

